server:
  port: 8085

spring:
  application:
    name: notification-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: rootpassword
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/chess_db
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
